### ISSUE TITLE
Specification of the rooms in a house

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/pipify#1]
I have asked you about this several times on Stackoverflow.

I need to know if your are OK with the way I am specifying the rooms (  https://github.com/JamesBremner/pipify?tab=readme-ov-file#specication-of-the-rooms-in-a-house )

Also, please look at the data files. ( https://github.com/JamesBremner/pipify/tree/main/dat ) Are you OK with this format?

**Comment by JamesBremner** [comment]
@RMTabish  Please answer this question.

I am ready to work on multiple room houses.  I need to ask you questions and receive prompt replies.  What is taking you so long?

**Comment by RMTabish** [comment]
Hey, I'm sorry for not being available there are some internet issues, so the goal is to find an approach to best fit the groups in the room, I'm attaching a PDF with the details about the project.
this may clear things up, also tonight I will be adding the project I made so far which includes loading the floor plan defining the points or corners of the rooms by simply clicking on the points and attaching all those points in a clockwise manner to make a closed shape, this way a room is segmented, plus appreciate the help.
[Plan of Approach for Underfloor Heating Layout Sof-4.pdf](https://github.com/user-attachments/files/16918355/Plan.of.Approach.for.Underfloor.Heating.Layout.Sof-4.pdf)

**Comment by JamesBremner** [comment]
Thanks for your response.

> best fit the groups in the room,

I do not know what you mean by "groups".  

> defining the points or corners of the rooms by simply clicking on the points

My question is about storing the points once you have clicked on them, or otherwise identified them.  Do you understand my proposal on how to do this?  My proposal is described here https://github.com/JamesBremner/pipify?tab=readme-ov-file#specication-of-the-rooms-in-a-house

**Comment by RMTabish** [comment]
here i made a demo for you 

https://github.com/user-attachments/assets/d4be5370-9101-437d-b18f-51d38209975a

**Comment by RMTabish** [comment]
I am storing the corner points of the floor plan as a list of coordinate points (x, y). Each corner point of a room or any other shape in the floor plan is represented as a 2D coordinate, where x is the horizontal position, and y is the vertical position.

These corner points are typically captured through user interactions (like mouse clicks) when defining room boundaries, and they are stored as a list of points. For example, in Python, the points could be stored as a list of tuples or arrays:
''''
room_points = [(x1, y1), (x2, y2), (x3, y3), (x4, y4)]
'''
This list of points can then be used to draw polygons representing the rooms or any shape, calculate areas, or generate spirals for underfloor heating layouts.

Each room or shape has its own list of corner points, allowing for flexibility in defining irregular or complex geometries

**Comment by RMTabish** [comment]
For the groups please open the pdf i shared 
Each room have groups  its like a spiral set a room cam have two or more or even one based on the user input for the width of group

**Comment by JamesBremner** [comment]
> Each room have groups its like a spiral

Can you please use the term "spiral" instead of "group".  This is much more self explanatory, and will not be confusing when talking about groups of other things.

Note that a convex room requires just one spiral.

![image](https://github.com/user-attachments/assets/2283ea12-8069-4db4-a125-69d728f4b769)

**Comment by JamesBremner** [comment]
> they are stored as a list of points. 

Yes, of course.  What I am trying to get your agreement on the details of this list:

Are the points stored in clockwise or anti-clockwise order?
Is the last point in the list the same as the first, or is the edge that closes the polygon implied?
How do you want to distinguish the points that specify the doors?

My proposal is: Each room is specified by a clockwise open polygon of 2D points ( Every corner is specified by one point, every door is specified by a pair of points. ) and a vector of indices in the polygon of the first point of a pair specifying a door

**Comment by RMTabish** [comment]
Yes you’re right, amazing work.
The key considerations are to keep in account the width of spiral and the bent radius of pupesbin corner, I highly recommend you go through the step 2 in pdf i shared

**Comment by JamesBremner** [comment]
> the width of spiral

The width of the spiral is the width of the room, or in the case of a concave room, the subroom.

> the bent radius of pipes at corner

Every pipe bend is 90 degrees.  If you want to calculate the exact position along  the radius of the bend, that is something that can be done in a post processing step - it is almost trivial compared to calculating the bend locations

**Comment by RMTabish** [comment]
Are the points stored in clockwise or anti-clockwise order? The points that define the corners of each room are stored in a clockwise order. This ensures consistency when generating pipe paths (like spirals) and when processing the room boundaries for visualization and pipe layout.
Is the last point in the list the same as the first, or is the edge that closes the polygon implied? The last point in the list is not necessarily the same as the first point. The polygon is closed by implied connection between the first and last points, so we don't duplicate the starting point in the list.
How do you want to distinguish the points that specify the doors? Each room is stored as a list of points representing its corners. For doors, we store them as pairs of points in the same list, representing the start and end points of the door along the boundary. We maintain a separate vector of indices to specify which points in the polygon correspond to doors, allowing us to distinguish them from regular room corners.
The width of the spiral: The width of the spiral pipes is based on the dimensions of the room, adjusted for consistent spacing between the pipes. For concave rooms (like L-shapes), the algorithm automatically adapts the spiral to fit within each subroom or concave section. We ensure that the pipes are distributed evenly across the entire floor space.
The bend radius of pipes at corners: The pipes have 90-degree bends by default at the corners. If you need precise positioning of bends along a curved path (i.e., a specific bend radius), this can be added in a post-processing step. However, for our current implementation, the main focus is on calculating the bend locations and ensuring the pipes avoid sharp turns while covering the room efficiently.

**Comment by JamesBremner** [comment]
Wow!  A simple yes would have done the job!

Please try to answer questions both promptly and briefly as you can.

**Comment by RMTabish** [comment]
I’ve recieved enough hate on stack for not being extra clear

**Comment by JamesBremner** [comment]
I am truly sorry about that. 

I have been on stackoverflow for many years.  It used to be a great place to get and offer help.  In recent years it has become full of horrible people who seem to spend their time being actively hateful.  Often questions are closed before I have a chance to answer them.  

Now we are on github we can relax and help each other.

**Comment by RMTabish** [comment]
Truly inspired by people like you
