### ISSUE TITLE
Input file format

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/pipify#2]
Given that

> Are the points stored in clockwise or anti-clockwise order? The points that define the corners of each room are stored in a clockwise order. This ensures consistency when generating pipe paths (like spirals) and when processing the room boundaries for visualization and pipe layout.
> Is the last point in the list the same as the first, or is the edge that closes the polygon implied? The last point in the list is not necessarily the same as the first point. The polygon is closed by implied connection between the first and last points, so we don't duplicate the starting point in the list.
> How do you want to distinguish the points that specify the doors? Each room is stored as a list of points representing its corners. For doors, we store them as pairs of points in the same list, representing the start and end points of the door along the boundary. We maintain a separate vector of indices to specify which points in the polygon correspond to doors, allowing us to distinguish them from regular room corners.
> The width of the spiral: The width of the spiral pipes is based on the dimensions of the room, adjusted for consistent spacing between the pipes. For concave rooms (like L-shapes), the algorithm automatically adapts the spiral to fit within each subroom or concave section. We ensure that the pipes are distributed evenly across the entire floor space.
> The bend radius of pipes at corners: The pipes have 90-degree bends by default at the corners. If you need precise positioning of bends along a curved path (i.e., a specific bend radius), this can be added in a post-processing step. However, for our current implementation, the main focus is on calculating the bend locations and ensuring the pipes avoid sharp turns while covering the room efficiently.

or more briefly

> Each room is specified by a clockwise open polygon of 2D points ( Every corner is specified by one point, every door is specified by a pair of points. ) and a vector of indices in the polygon of the first point of a pair specifying a door

we need to talk about the input file format.  ( The input file would be used for, among other things, transferring room specification from your program that load the the floor plan and clicks on the corners and doors to my program that calculated the pipe layout )

I propose:

A space delimited text file
Each room is introduced by a line `room room_name`
Each room corner and door jam ( the wall points ) is specified by a line `x y`
Each door is is specified by a line `index of first door jam in wallpoints`

for example

```
room one
0 0
10 0
30 0
100 0
100 100
0 100
1
room two
100 0
110 0
130 0
200 0
200 100
100 100
1
```

**Comment by RMTabish** [comment]
The points defining each room's corners are stored in clockwise order. The polygon is closed by connecting the first and last points, so we don’t repeat the first point. Doors are represented as pairs of points within the list of room corners, and we use a separate vector of indices to indicate where the doors are located along the boundary.

Regarding the spiral width, it is based on the room’s dimensions with consistent spacing, and the pipe layout adapts for concave rooms. The pipe bends are 90-degree turns, but if precise bend radii are needed, this can be handled in post-processing.

Your proposed text file format sounds good for transferring room and door specifications between our systems.

**Comment by JamesBremner** [comment]
If the answer is yes, just say yes.

I will now implement this.

Perhaps you could do whatever modifications to your program that are required to output a file in this format.  I look forward to testing on some real data.

**Comment by JamesBremner** [comment]
This input

```
room one
0 0
10 0
30 0
100 0
100 100
0 100
1
room two
100 0
110 0
130 0
200 0
200 100
100 100
1
```

gives

![image](https://github.com/user-attachments/assets/8f9afdf2-1576-4574-82e9-6d3dd664e228)
