### ISSUE TITLE
Rooms must ALWAYS be connected directly to furnace room by a door.

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/pipify#3]
The simplest possible multi-room house

![image](https://github.com/user-attachments/assets/b30e2cbb-aa6f-41cf-aa13-3c4d9ace1514)

So, how do you want to connect the spirals in the rooms of a house?

( a rough sketch of how you think this should look would be a good initial answer. We can discuss picky details later  )

Do you want the layout to be a single long pipe snaking into and out of every room?  Seems like this would result in some rooms being too hot and some too cold.

Or do you want several pipes 'radiating' out from a furnace location?  This might allow the temperature in each room to be independently controlled.

**Comment by RMTabish** [comment]
i don't understand how the first approach will result in some rooms being too hot and some too cold

**Comment by JamesBremner** [comment]
As the heated fluid travels through a pipe it gives up heat to the room.  So the fluid is colder when it leaves the room than when it entered.  If the rooms are laid out in series, so that one pipe snakes from the furnace through all the rooms one by one before returning to the furnace to be reheated, then each room will be colder than the one before.

Also, if the first room is too hot, the occupants of that room will turn down the fluid flow.  That means the flow through the remaining rooms will also be reduced, leaving them even colder.

There are actually three options:

1. All rooms are heated in series
2. All rooms are connected directly and independently to the furnace ( a star pattern )
3. Rooms are heated in parallel from ring

![image](https://github.com/user-attachments/assets/64c82966-bde3-44ea-aee4-19c88d9d6744)

I would think that number 3, the ring pattern, would be the most effective.

**Comment by RMTabish** [comment]
you're right, the third one is the better option

**Comment by RMTabish** [comment]
<img width="238" alt="Screenshot 2024-08-30 104204" src="https://github.com/user-attachments/assets/eceb4743-541a-4242-8987-2a6018bdc426">

**Comment by JamesBremner** [comment]
I still cannot see the furnace, nor can I see the pipe connecting the room

**Comment by RMTabish** [comment]
here the verdeler is the furnace, its the distributor from where each spiral is going out and joins back in.
as mentioned in doc below 
'Because everything is made to scale, I also want the connection point (distributor(verdeler)) to be 
scaled accordingly in the output drawing. Therefore, input must be provided for this. The input is 
divided into A = Initial Length (mm), B1 = Group Width (mm), B2 = Number of Groups on the 
Distributor, and C = End Length (mm), X = 
Desired Number of Groups. Distributor Length 
= A + (B1 * B2) + C, but this is only the case if 
B2 == X. If X > B2, then an additional 
distributor must be added to the layout. For 
the second distributor, ask the user for the 
specifications: A_2 (Initial Length (mm)), B1_2 
(Group Width (mm)), B2_2 (Number of Groups 
on the Distributor), and C_2 (End Length 
(mm)) of the new distributor, and add it in the 
same way until X <= B2.'

I'm taking all the input from the user for the verdeler(distributor  or furnace)

**Comment by JamesBremner** [comment]
I was supposed to guess that 'verdeler' was the furnace?????

Please post a sketch annotated in English so that I can understand it.  Show the pipes leading from the furnace to the rooms **only** so I can see them.  All the spiral lines are not only incorrect but they confuse the picture that I need to see.

**Comment by JamesBremner** [comment]
Here is the sort of diagram I need from you

![image](https://github.com/user-attachments/assets/5c9c94ff-6802-4698-97eb-c7d6bc671900)

**Comment by RMTabish** [comment]
Its never the case that room isn't approachable by furnace, humans work with it
They decide the location for it so its always at the place most optimal for all the rooms

**Comment by JamesBremner** [comment]
No where in your document does it say the 'verdeler' is the furnace.  It talks about a 'connection point' which means nothing to me.

**Comment by RMTabish** [comment]
It does not say that in documentation, thats why i typed it out in comment

**Comment by JamesBremner** [comment]
>  never the case that room isn't approachable by furnace, humans work with it

I think you mean that the furnace room is approachable by humans.  Please proof read before posting.

The point I am trying to make is that not every room in a house needs to be connected DIRECTLY to the furnace room.  The furnace room can be approached by humans through a series of rooms, one after the other.

![image](https://github.com/user-attachments/assets/12ea86ba-97cd-4774-94c0-e91a03218c2b)

**Comment by JamesBremner** [comment]
> Please instead of assuming things try asking for explainations

That's what I opened this issue for.  That is why I labelled this issue "question" and assigned it to you.

**Comment by JamesBremner** [comment]
> I meant rooms are always directly connected with the furnace room.

OK, if that is what you want, I can certainly restrict the possible room layouts in this way.

**Comment by RMTabish** [comment]
Perfect

**Comment by JamesBremner** [comment]
![image](https://github.com/user-attachments/assets/aba3f2ee-1dc8-41dd-9b5f-207e9029c882)

**Comment by JamesBremner** [comment]
I am working on fixing the gaps in the return pipe #6 

Otherwise, does this look correct to you?

**Comment by JamesBremner** [comment]
I posted my proposal for the furnace room pipe layout two days ago https://github.com/JamesBremner/pipify/issues/3#issuecomment-2339378408

There has been no response.

In the meantime, I have been working on getting the details right #6.  You can test this under that issue.

Closing this one, replaced by #6

**Comment by RMTabish** [comment]
> I posted my proposal for the furnace room pipe layout two days ago [#3 (comment)]

I don't understand, you just posted there output, note that as shared in the doc the furnace room can also have the heating floor

**Comment by JamesBremner** [comment]
You can check when a post was made by looking at the header.

![image](https://github.com/user-attachments/assets/3e7d64aa-fcde-4f9b-8b8b-59351b77f781)
