### ISSUE TITLE
Real input file

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/pipify#4]
I have created some test input files https://github.com/JamesBremner/pipify/tree/main/dat

We need to test a 'real' input file, that is one that comes from your program to convert the floor plans into co-ordinates for the room walls and doors.

Input file format:

A space delimited text file
Each room is introduced by a line `room room_name`
Each room corner and door jam ( the wall points ) is specified by a line `x y`
Each door is is specified by a line `index of first door jam in wallpoints`
The furnace room is specified by a line `furnace room_name`

How is the work on that coming along?

I have looked for the repository in your github profile, but cannot find it.  Have you marked it private?  If so, maybe you could invite me on as a collaborator?

**Comment by RMTabish** [comment]
I haven't pushed the code on GitHub but I can make a private repo if you think that would help. 
We can make a demo test file for it or use the Python application to feed the coordinates to c++ program, I can write a script for it, or again we have the manual testing option so we can care about integrating later and test the functionality first.

**Comment by JamesBremner** [comment]
Perhaps I misunderstood.  I thought you were developing an application to load floor plans so that a user could click on the plan to identify the doors and corners of the rooms.

From your 'Plan of approach' document, step 1

> Design an interface for users to input room coordinates

Have you done this?

**Comment by JamesBremner** [comment]
>  we can care about integrating later and test the functionality first.

It is very important to do integration testing as soon as possible.

Integration testing often reveals major errors and misunderstandings that require the re-design and re-writing of application code.  If left too late then the result can be lengthy and unexpected delays to the first production release.

The best approach is to build "black boxes" that do little more than produce output and consume input using the agreed upon communication format.  Once integration testing is successful, then the black boxes can have features added to them so that they perform real work with confidence that they will not have to rewritten at the last minute.

Please let me know as soon as possible when your floor plan processor is ready to output real files containing the locations of walls and doors.

**Comment by RMTabish** [comment]
yes i implemented this part already please see the demo I recorded for you

**Comment by JamesBremner** [comment]
That's great.

Please post the output from your application so I can test **pipify** with some real data.

**Comment by RMTabish** [comment]
as I told you earlier I'm storing the room points (that you can assume any shape like you uploaded in read me ) and then the door are also stored in a heap so you can hardcode that too, there's non output from the program that you can feed to your code to identify any useful information.

**Comment by JamesBremner** [comment]
>  there's no output from the program

Why not?  How do you expect **pipify** to obtain the locations of the walls and doors from your floor plan processor?

**Comment by JamesBremner** [comment]
I want you to give me an output as described in the first post to this issue https://github.com/JamesBremner/pipify/issues/4#issue-2518055609

for reference, here it is once again

A space delimited text file
Each room is introduced by a line `room room_name`
Each room corner and door jam ( the wall points ) is specified by a line `x y`
Each door is is specified by a line `index of first door jam in wallpoints`
The furnace room is specified by a line `furnace room_name`

For an example, look at any of the test files in the `dat` folder

Here is the star house test file

```

room one
100 100
140 100
160 100
200 100
200 140
200 160
200 200
160 200
140 200
100 200
100 160
100 140
1
4
7
10
room two
100 0
200 0
200 100
160 100
140 100
100 100
3
room left
0 100
100 100
100 140
100 160
100 200
0 200
2
room right
200 100
300 100
300 200
200 200
200 160
200 140
4
room bottom
100 200
140 200
160 200
200 200
200 300
100 300
1
furnace one
```

which looks like this

![image](https://github.com/user-attachments/assets/1d5f5c01-0084-4fdc-a2f8-5f5be23b415b)

**Comment by RMTabish** [comment]
I would have to make some major application changes to get the output you mentioned, is there a way to test your solution with rooms that are of not square shapes only?

**Comment by JamesBremner** [comment]
The rooms can be of any shape you want, so long as the walls are horizontal or vertical.  Take a look at https://github.com/JamesBremner/pipify/blob/main/dat/ex1.txt

It is a lot of trouble creating the test files by hand.  So, to keep things simple, I tend to create square rooms if I am not explicitly testing rooms of other shapes.  This is one of many reasons why we need to test against real data from your application.

**Comment by JamesBremner** [comment]
Your post https://github.com/JamesBremner/pipify/issues/4#issuecomment-2344641786 is garbled.

**Comment by RMTabish** [comment]
![image](https://github.com/user-attachments/assets/4a82ae7c-2467-47ed-acd0-2d64dcdad893)

**Comment by RMTabish** [comment]
would your solution work for the rooms of this shape?
also can you please share any better means I can communicate with you?

**Comment by JamesBremner** [comment]
Do you mean concave rooms ( i.e. L-shaped rooms )?

Please read the README.  https://github.com/JamesBremner/pipify#pipe-layout-in-a-l-shaped-room

**Comment by RMTabish** [comment]
yes
in the readme the visualization for the concave room is quite different than the one you shared above where there are two pipes in parallel

**Comment by JamesBremner** [comment]
There are no concave rooms in this thread.  You yourself pointed out that they were all square.  

> there are two pipes in parallel

Yes.  The red is the hot pipe from the furnace, the blue is the cold return.

**Comment by RMTabish** [comment]
I don't understand, why the program does not work for concave-shaped rooms.
I don't remember saying it shouldn't

**Comment by JamesBremner** [comment]
Pipify **does** work for concave rooms.  As shown by the image posted to the README.

**Comment by JamesBremner** [comment]
I just took another look at your githib profile.  I still cannot see your repository for this project.

Any word on how long before you will have some real test files for me?

**Comment by RMTabish** [comment]
i was trying out the ways i can change the application to get the output files from the last day but was unable to do so, can you help me on how I can make the test file manually?

**Comment by JamesBremner** [comment]
Please do NOT make the test files manually.  I am already doing this, so there is no need for you to do it as well.

We need to do an integration test.  

We need to test that your application can output files that **pipify** can read accurately.  Until, that is successful, then the two applications cannot do anything useful.

**Comment by JamesBremner** [comment]
I would be happy to advise on modifying your code to output the files needed by pipify.  

To do that, of course, I would need to see your code.  Please publish your github repo and invite me to collaborate with you there.

**Comment by JamesBremner** [comment]
Hello?  Anything happening at your end?

**Comment by JamesBremner** [comment]
This issue has now been assigned to you for exactly a week.   Are you working on it?  Do you need my help?

**Comment by RMTabish** [comment]
I won't be able to work on it till Tuesday

**Comment by RMTabish** [comment]
please share your number or telegram, i don't check e-mail on daily basis

**Comment by JamesBremner** [comment]
Two weeks this issue has been open, and nothing has been done.  Closing.
