### ISSUE TITLE
No room has multiple doors

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/pipify#5]
Every room must have a door to the furnace room.  ( see #3 )

However, I assume that rooms may have more than one door.

Options:

 - Your floor plan processor will ignore all other doors than one for each room that connects to the furnace room.  I can add a sanity check that will raise an error if a room has more than one door.
 - Your floor plan processor will identify the furnace room doors.  We will need to discuss how you want to that.
 - **Pipify** can work out which door in a multi-door room connects to the furnace room

Please let me know which option you want to use.

**Comment by RMTabish** [comment]
'''However, I assume that rooms may have more than one door.'''

this is not the case, I don't know If I wasn't clear enough or if you weren't able to understand
all the instructions like where the room is where the door is, and where to place the distributor were given by the user, please see the video I attached earlier.

**Comment by JamesBremner** [comment]
Wow!  How very strange.  

Every room in your house has just one door and that door leads into the furnace room!  How do people get in and out of your house?

Well, OK, I will add a check to raise an error if any room has more than one door.

**Comment by RMTabish** [comment]
> Wow! How very strange.
> 
> Every room in your house has just one door and that door leads into the furnace room! How do people get in and out of your house?
There's no need to be sarcastic but to read again what I typed, I said the user marks the room and doors and furnace, it is a tool to be used by humans, not others.

**Comment by JamesBremner** [comment]
>  user marks the room and doors 

I think that it was reasonable for me to assume that the user would mark every door.  You might be expecting too much of your users to expect them to mark ONLY doors that connect to the furnace room.

**Comment by JamesBremner** [comment]
You can see all the issues that are currently open and assigned to you if you open this page https://github.com/JamesBremner/pipify/issues?q=assignee%3ARMTabish+is%3Aopen

**Comment by JamesBremner** [comment]
No response, so I assume that you are happy with this.
